version: "3.3"

services:

  elasticsearch:
    command: elasticsearch -Enetwork.host=0.0.0.0 -Ediscovery.zen.ping.unicast.hosts=elasticsearch
    environment:
      ES_JAVA_OPTS: -Xms2g -Xmx2g
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
    ports:
      - "9200:9200"
    ulimits:
      memlock: -1
      nofile:
        hard: 65536
        soft: 65536
      nproc: 65538
    volumes:
      - /usr/share/elasticsearch/data
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.2
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      test: wget -qO- http://localhost:5601 > /dev/null
      interval: 30s
      retries: 3
  logstash:
    hostname: logstash
    command: sh -c "logstash -e 'input { beats { port => 5044 } } output { elasticsearch { hosts => "elasticsearch:9200"} } '"
    image: logstash:alpine
    ports:
        - "5044:5044/tcp"
        - "5044:5044/udp"
        - "12201:12201/udp"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 2

networks:
  elk:
    driver: overlay
    driver_opts:
      encrypted: "true"
